version: '3.3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3120:3120"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "ruby:3.1.3"
    volumes:
      - db-data:/data/db
volumes:
  db-data: